baseURL = "https://gregbair.dev/"
languageCode = "en-us"
title = "Greg Bair"
theme = "hello-friend"

[params]
    defaultTheme = "dark"
    shoreadingTime = true
    showMenuItems = 2

[languages]
  [languages.en]
    title = "Greg Bair"

  [languages.en.params.logo]
    logoText = "Greg Bair"
    logoHomeLink = "/"