baseURL = "https://gregbair.dev/"
languageCode = "en-us"
title = "GregBair.Dev - A developer's blog"
theme = "ezhil"

# Enable syntax highlighting.
pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disableDisqusTypes = ["page","posts"]

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/gregbair"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/gregbair"

[[params.social]]
name = "Gitlab"
icon = "gitlab"
url = "https://gitlab.com/gregbair"