baseURL = "https://gregbair.dev/"
languageCode = "en-us"
title = "GregBair.Dev - A developer's blog"
theme = "binario"
paginate = "10"

[Author] # Used in authorbox
  name = "Greg Bair"
  bio = "John Doe's true identity is unknown. Maybe he is a successful blogger or writer."

# Enable syntax highlighting.
pygmentsstyle = "dracula"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[permalinks]
# posts = "/posts/:year/:month/:title/"
