baseURL = "https://gregbair.dev/"
languageCode = "en-us"
title = "GregBair.Dev - A developer's blog"
theme = "ezhil"

# Enable syntax highlighting.
pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disableDisqusTypes = ["page","post"]